# Generated by Django 2.0.2 on 2019-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='isCandidate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
