# Generated by Django 2.0.2 on 2019-03-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_investor_iscandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_mummy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
