# Generated by Django 2.0.2 on 2019-03-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190308_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Investor'),
        ),
    ]
